# Use the official PostgreSQL image as the base
FROM postgres:latest

# Copy the initialization script to the Docker container
COPY init-pg-replica.sh /docker-entrypoint-initdb.d/init-pg-replica.sh

# Make the script executable
RUN chmod +x /docker-entrypoint-initdb.d/init-pg-replica.sh
